{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import re\n",
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 notifications total\n",
      "\n",
      "Skip to search\n",
      "\n",
      "Skip to main content\n",
      "\n",
      "Close jump menu\n",
      "Search\n",
      "Primary Navigation\n",
      "Home\n",
      "My Network\n",
      "Jobs@linkedin.com \n",
      "Messaging\n",
      "13\n",
      "13 new notifications\n",
      "Notifications\n",
      "Rabindra Kharel\n",
      "Me\n",
      "\n",
      "Work\n",
      "Advertise\n",
      "Photo of Rabindra Kharel\n",
      "Rabindra Kharel\n",
      "Senior Data Engineer\n",
      "\n",
      "Who viewed your profile\n",
      "238\n",
      "Views of your post\n",
      "567\n",
      "Access exclusive tools & insights\n",
      "Retry Premium Free\n",
      " My items\n",
      "\n",
      "Fort Services logo\n",
      "Fort Services\n",
      "Page notifications\n",
      "5\n",
      "Page visitors\n",
      "1\n",
      "See visitor analytics\n",
      "Recent\n",
      "\n",
      "CX Network: Customer Experience, Service, Insight, Digital and Marketing Leaders\n",
      "Data Analytics - Big Data • BI • SQL • Power BI • Tableau • RPA • Python • ML • AI • Azure • DevOps\n",
      "Oracle Retail Q&A\n",
      "Oracle Retail Analytics Professional\n",
      "Use it or Lose it: Data Science Best Practices to Leverage AI/ML\n",
      "GroupsSee all Groups\n",
      "\n",
      "CX Network: Customer Experience, Service, Insight, Digital and Marketing Leaders\n",
      "Data Analytics - Big Data • BI • SQL • Power BI • Tableau • RPA • Python • ML • AI • Azure • DevOps\n",
      "Oracle Retail Q&AShow more Show more Groups\n",
      "EventsSee all Events Contact: gregor@mxanalytics.com \n",
      "\n",
      "\n",
      "Havard Business School - Startup Demo DaySee allSee all Events\n",
      "Followed HashtagsSee all Followed Hashtags\n",
      "Discover more\n",
      "Visit profile for Rabindra Kharel\n",
      "\n",
      "Start a post\n",
      "\n",
      "Photo\n",
      "\n",
      "Video\n",
      "Event\n",
      "\n",
      "Write article\n",
      "\n",
      "Sort by:\n",
      "Top\n",
      "Feed Updates\n",
      "Feed post number 1\n",
      "kshitij’s profile photo\n",
      "kshitij khanal commented on this\n",
      "\n",
      "Anup NepalStatus is reachable\n",
      "Anup Nepal\n",
      "• 1st\n",
      "Digital Transformation\n",
      "7h • 7 hours ago\n",
      "I’m happy to share that I’m starting a new position as Retail Optimization Lead at Tango Energy!\n",
      "\n",
      "Starting a New Position\n",
      "likecelebrate\n",
      "27\n",
      "Shreya Basnyat and 26 others\n",
      "8 comments\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Rabindra Kharel\n",
      "\n",
      "\n",
      "\n",
      "Open Emoji Keyboard\n",
      "\n",
      "Current selected sort order is Most relevant\n",
      "Most relevant\n",
      "susan.daniels@moo.com \n",
      " 1st degree connection1st\n",
      "Software Engineer\n",
      "2h\n",
      "Congrats bro!\n",
      "\n",
      "\n",
      "Like\n",
      "\n",
      "Reply\n",
      "\n",
      "Load more comments\n",
      "Feed post number 2\n",
      "Nithesh Suvarna follows Hevo Data\n",
      "\n",
      "Hevo Data\n",
      "Hevo Data\n",
      "33,425 followers\n",
      "Promoted\n",
      "There is an easier way to perform Redshift ETL.\n",
      "\n",
      "Find out how you can save time on engineering and research to set-up Redshift ETL with our cheatsheet.\n",
      "…see more\n",
      "\n",
      "Free guide to Redshift ETL\n",
      "hevodata.com\n",
      "\n",
      "Download. View Sponsored Content\n",
      "Download\n",
      "like\n",
      "40\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "\n",
      "Be the first to comment on this\n",
      "\n",
      "Feed post number 3\n",
      "Profile images for several LinkedIn members\n",
      "Profile images for several LinkedIn membersProfile images for several LinkedIn members\n",
      "Rajan Upadhyay and Subin Shrestha like this\n",
      "\n",
      "Gunjan ShakyaStatus is reachable\n",
      "Gunjan Shakya\n",
      "• 1st\n",
      "Software Engineer\n",
      "2d • 2 days ago\n",
      "Just finished the course “Communicating with Confidence” by Jeff Ansell! Check it out: https://lnkd.in/ejtCuJMK #publicspeaking #wellness.\n",
      "\n",
      "Certificate of Completion\n",
      "linkedin.com • 1 min read\n",
      "like\n",
      "10\n",
      "Rajan Upadhyay and 9 others\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "\n",
      "Be the first to comment on this\n",
      "\n",
      "Feed post number 1\n",
      "Aayush AdhikariStatus is online\n",
      "Aayush Adhikari\n",
      "• 1st\n",
      "Machine Learning Data Scientist at DeepMind Creations Pvt Ltd\n",
      "8h • Edited • 8 hours ago\n",
      "\n",
      "Hello all our company is opening for PAID INTERNSHIP on Flutter. If you are interested plz send your CV at aayush@deepminds.xyz\n",
      "\n",
      "#flutter\n",
      "#flutterdeveloper\n",
      "#ml\n",
      "#ai\n",
      "…see more\n",
      "likesupport\n",
      "12\n",
      "1 comment\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Feed post number 2\n",
      "Jobs recommended for you\n",
      "\n",
      "View job: Senior Data Engineer\n",
      "\n",
      "Recruiting from Scratch\n",
      "Senior Data Engineer\n",
      "Recruiting from Scratch\n",
      "Vancouver, British Columbia, Canada\n",
      "\n",
      "1 month ago\n",
      "View job: Senior Data Engineer - Scala/AWS\n",
      "\n",
      "Jobot\n",
      "Senior Data Engineer - Scala/AWS\n",
      "Jobot\n",
      "Vancouver, British Columbia, Canada\n",
      "\n",
      "1 week ago •  Easy Apply\n",
      "View job: Senior Big Data Engineer\n",
      "\n",
      "Emonics LLC\n",
      "Senior Big Data Engineer\n",
      "Emonics LLC\n",
      "Vancouver, British Columbia, Canada\n",
      "send email to hr@vancuemonics.com \n",
      "\n",
      "3 days ago •  Easy Apply\n",
      "\n",
      "See moreSee more\n",
      "Feed post number 3\n",
      "Santosh’s profile photo\n",
      "Santosh Pandey likes this\n",
      "\n",
      "Jagrit Gambhir\n",
      "Jagrit Gambhir\n",
      "• 3rd+\n",
      "☀️ Solving for Future of Work | People Engagement\n",
      "3d • 3 days ago\n",
      "Follow\n",
      "Hypocrisy 101\n",
      "\n",
      "\"How soon can you join? We need somebody who can join within a week.\"\n",
      "\n",
      "\"You'll need to serve 3 months of notice period, we can't do anything about it.\"\n",
      "\n",
      "If the employee is so important to you that you need 3 months to replace them, you should've treated them well in the first place - and they probably wouldn't have left.\n",
      "\n",
      "A smooth exit process is underrated.\n",
      "\n",
      "Do it well, and the employee might consider returning in the future.\n",
      "\n",
      "Make it complicated, and the employee will ensure that none of their friends/acquaintances ends up joining your company ever again. 🙃\n",
      "\n",
      "Curious, how was your exit process in your previous org?\n",
      "\n",
      "#noticeperiod #offboarding #employeeexperience\n",
      "…see more\n",
      "\n",
      "No alternative text description for this imageActivate to view larger image\n",
      "likecelebratesupport agent syneca.gregory@gmail.com \n",
      "1,420\n",
      "Santosh Pandey and 1,419 others\n",
      "87 comments\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Feed post number 4\n",
      "Chandan Gupta Bhagat, Amit Raj Sapkota and 136 other connections follow The British College, Kathmandu\n",
      "\n",
      "The British College, Kathmandu\n",
      "The British College, Kathmandu\n",
      "4,662 followers\n",
      "Promoted\n",
      "TBC is proud to announce the second series of the TBC Distinguished Guest Lecture Series with Prof Tim Gocher & Dr Sujit Pandey. The topic of the session: \"Innovation, Development & Covid 19: Post Pandemic Context for Nepal.\"\n",
      "RSVP: https://bit.ly/33jYiV1\n",
      "…see more\n",
      "No alternative text description for this image\n",
      "TBC Distinguished Guest Lecture Series II\n",
      "Apply Now. View Sponsored Content\n",
      "Apply Now\n",
      "No alternative text description for this image\n",
      "TBC Distinguished Guest Lecture Series II\n",
      "Apply Now. View Sponsored Content\n",
      "Apply Now\n",
      "No alternative text description for this image\n",
      "TBC Distinguished Guest Lecture Series II\n",
      "Apply Now. View Sponsored Content\n",
      "Apply Now\n",
      "\n",
      "like\n",
      "25\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "\n",
      "Be the first to comment on this\n",
      "\n",
      "Feed post number 5\n",
      "Congratulate Sunil Rijal on their work anniversary\n",
      "\n",
      "Sunil Rijal\n",
      "Sunil Rijal\n",
      "• 1st\n",
      "CEO and Founder at SoftNEP\n",
      "1d1 day ago\n",
      "Celebrating 17 years at SoftNEP Pvt Ltd\n",
      "celebratelike\n",
      "2\n",
      "\n",
      "Congrats Sunil\n",
      "\n",
      "Time flies!\n",
      "\n",
      "Kudos to you\n",
      "\n",
      "Wow!\n",
      "\n",
      "What an achievement!\n",
      "\n",
      "Great work!\n",
      "\n",
      "Wow, 17 years already?\n",
      "\n",
      "Scroll right\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "Rabindra Kharel\n",
      "\n",
      "\n",
      "\n",
      "Open Emoji Keyboard\n",
      "\n",
      "Feed post number 6\n",
      "Lekhanath’s profile photo\n",
      "Lekhanath Bhandari commented on this\n",
      "\n",
      "Connie Burke\n",
      "Connie Burke\n",
      "• 3rd+\n",
      "Director, Eurest\n",
      "3d • 3 days ago\n",
      "I am looking to fill the following jobs:\n",
      "Sous Chef\n",
      "Grill Cook\n",
      "Prep Cook\n",
      "\n",
      "Monday-Friday\n",
      "Hanover Maryland\n",
      "PM me for details\n",
      "…see more\n",
      "likelove\n",
      "166\n",
      "132 comments\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Rabindra Kharel\n",
      "\n",
      "\n",
      "\n",
      "Open Emoji Keyboard\n",
      "\n",
      "Current selected sort order is Most relevant\n",
      "Most relevant\n",
      "See profile for Lekhanath BhandariStatus is reachable\n",
      "Lekhanath Bhandari\n",
      " 1st degree connection1st\n",
      "sous chef at fazlani nature nest\n",
      "1d\n",
      "Interested for sous chef\n",
      "\n",
      "\n",
      "Like\n",
      "\n",
      "Reply\n",
      "\n",
      "Load more comments\n",
      "Feed post number 7\n",
      "Bibek’s profile photo\n",
      "Bibek Mahatara likes this\n",
      "\n",
      "Anthony J JamesStatus is reachable\n",
      "Anthony J James\n",
      "• 2nd\n",
      "CEO, Innovation and Growth at Trinity Consulting - Founder, InfluencerActive, the World's First B2B Influencer Marketplace\n",
      "12h • 12 hours ago\n",
      "Follow\n",
      "Turn your plants into pets!\n",
      "\n",
      "Play\n",
      "Back to start of video\n",
      "Skip back 10 seconds\n",
      "Skip ahead 10 seconds\n",
      "Current time 0:00/Duration 0:45\n",
      " \n",
      "1x\n",
      "\n",
      "Playback speed\n",
      "\n",
      "Unmute\n",
      "\n",
      "Turn fullscreen on\n",
      "likeloveinsightful\n",
      "9,044\n",
      "Bibek Mahatara and 9,043 others\n",
      "257 comments\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Feed post number 1\n",
      "Larange’s profile photo\n",
      "Larange Tiwari likes this\n",
      "\n",
      "Eric Vyacheslav\n",
      "Eric Vyacheslav\n",
      "• 2nd\n",
      "Research Scientist at Google DeepMind • Advisor at AlphaSignal.ai\n",
      "1d • Edited • 1 day ago\n",
      "Follow\n",
      "Hi all!\n",
      "We're currently looking for a part time (4 hours/week) Computer Science PhD or Masters student to help us at https://alphasignal.ai\n",
      "\n",
      "A few criteria:\n",
      "-Must be between timezones GMT+5 (India) to GMT+9 (Japan).\n",
      "-Published at least one research paper in Machine Learning.\n",
      "-Has some familiarity with Pytorch, Tensorflow.\n",
      "-Knows the difference between RNN, CNN, LSTM, GANs.\n",
      "-Familiarity with Deep Learning terms.\n",
      "-Knows about Meta AI, Deepmind, Google AI, OpenAI and other big players.\n",
      "\n",
      "That's it!\n",
      "If you know a student who fits the role send it my way :)\n",
      "\n",
      "It's definitely a resume-booster.\n",
      "…see more\n",
      "likesupportcurious\n",
      "432\n",
      "Larange Tiwari and 431 others\n",
      "102 comments\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Feed post number 2\n",
      "Reena koju and Santosh Bhattarai follow Spot by NetApp\n",
      "\n",
      "Spot by NetApp\n",
      "Spot by NetApp\n",
      "11,440 followers\n",
      "Promoted\n",
      "Download our free digital guide to Microsoft Azure. Learn best practices for architecting and managing efficient, scalable cloud infrastructure built to accelerate your business\n",
      "…see more\n",
      "\n",
      "Getting Started with Azure Cloud Infrastructure – Get the PDF Guide\n",
      "get.spot.io\n",
      "\n",
      "Download. View Sponsored Content\n",
      "Download\n",
      "like\n",
      "30\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "\n",
      "Be the first to comment on this\n",
      "\n",
      "Feed post number 3\n",
      "Everest’s profile photo\n",
      "Everest K.C. likes this\n",
      "\n",
      "Santosh Yadav\n",
      "Santosh Yadav\n",
      "• 2nd\n",
      "System Administrator\n",
      "6h • Edited • 6 hours ago\n",
      "Bikash Bhandari Sir is an extremely experienced DevOps engineer. He has an intelligent teaching method, Start teaching from the very basics to taking to a stage where you build real-world solutions and debug challenges. The designed labs were great and worked as expected without a hitch. Thanks, owlocular to give me this certificate.\n",
      "…see more\n",
      "Your document has finished loading\n",
      "likecelebratelove\n",
      "6\n",
      "Everest K.C. and 5 others\n",
      "1 comment\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Feed post number 4\n",
      "Lalit’s profile photo\n",
      "Lalit Sharma commented on this\n",
      "\n",
      "Javedul Islam\n",
      "Javedul Islam\n",
      "• 3rd+\n",
      "Commissioning Manager - Process | Commissioning Expert | Troubleshooting Expert for O&M|\n",
      "20h • 20 hours ago\n",
      "Riyadh AldhaleaiStatus is reachable\n",
      "Riyadh Aldhaleai\n",
      "• 3rd+\n",
      "Manager -Manpower Services at AlMansoori Specialized Engineering\n",
      "3d • 3 days ago\n",
      "Follow\n",
      "small test for your focus\n",
      "whats is the Number inside the circle?\n",
      "\n",
      "Image previewActivate to view larger image\n",
      "like\n",
      "4\n",
      "18 comments\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Rabindra Kharel\n",
      "\n",
      "\n",
      "\n",
      "Open Emoji Keyboard\n",
      "\n",
      "Current selected sort order is Most relevant\n",
      "Most relevant\n",
      "See profile for Lalit SharmaStatus is reachable\n",
      "Lalit Sharma\n",
      " 1st degree connection1st\n",
      "Team Leader cum Senior Highway Engineer\n",
      "1h\n",
      "45283\n",
      "\n",
      "\n",
      "Like\n",
      "\n",
      "Reply\n",
      "\n",
      "Load more comments\n",
      "Feed post number 5\n",
      "Sammeer’s profile photo\n",
      "Sammeer Gaikwad loves this\n",
      "\n",
      "Mehrtash Soltani, Ph.D\n",
      "Mehrtash Soltani, Ph.D\n",
      "• 2nd\n",
      "Social Media Marketing|Please click FOLLOW button for the latest development in Civil Engineering || 230K+ Followers ||\n",
      "23h • 23 hours ago\n",
      "Follow\n",
      " What Causes Breakdowns in Traffic Flow?\n",
      "\n",
      "The layman's definition of congestion is \"too many cars trying to use a highway at the same time\". Transportation engineers formalize this idea as capacity—the ability to move vehicles past a point over a given span of time. When the capacity of a highway section is exceeded, traffic flow breaks down, speeds drop, and vehicles crowd together. These actions cause traffic to back up behind the disruption.\n",
      "\n",
      "Basically, there are three types of traffic flow behavior that will cause traffic flow to break down:\n",
      "\n",
      "1- \"Bunching\" of vehicles as a result of reduced speed.\n",
      "2- Intended Interruption to Traffic Flow.\n",
      "3- Vehicle Merging Maneuvers. \n",
      "\n",
      "With all this information, I believe this dog got the concept and found the solution better than me as a Highway engineer ;)\n",
      "\n",
      "If you found the content informative, you may Follow me by Mehrtash Soltani, Ph.D  for more!\n",
      "\n",
      "Video Credit: IG @ earthdixe\n",
      ".......................................................................\n",
      "All rights and credits are reserved to the respective owner(s). If you are the main copyright owner rather than the one mentioned here of this content, contact me to claim credit or content removal.\n",
      "\n",
      "Check out #mehrtashsoltani for educational and practical content in civil engineering!\n",
      "…see more\n",
      "\n",
      "Pause\n",
      "Back to start of video\n",
      "Skip back 10 seconds\n",
      "Skip ahead 10 seconds\n",
      "Current time 0:04/Duration 0:18\n",
      " \n",
      "1x\n",
      "\n",
      "Playback speed\n",
      "\n",
      "Unmute\n",
      "\n",
      "Turn fullscreen on\n",
      "likelovecelebrate\n",
      "3,781\n",
      "Sammeer Gaikwad and 3,780 others\n",
      "178 comments\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Feed post number 6\n",
      "Supermetrics\n",
      "Supermetrics\n",
      "13,205 followers\n",
      "Promoted\n",
      "\n",
      "Supermetrics has been listed on G2 as the highest rated marketing data pipeline company of 2022.\n",
      "\n",
      "Over 17,000 companies already use Supermetrics to streamline marketing reports.\n",
      "\n",
      "Join our happy customers and start your free trial today!\n",
      "…see more\n",
      "\n",
      "Start your free trial today\n",
      "supermetrics.comRegister. View Sponsored Content\n",
      "Register\n",
      "likelove\n",
      "61\n",
      "1 comment\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "Feed post number 7\n",
      "Samundra’s profile photo\n",
      "Samundra Shrestha loves this\n",
      "\n",
      "Daniel Abrahams\n",
      "Daniel Abrahams\n",
      "• 2nd\n",
      "Here to write. If it goes viral, it's not because of me. It's because it's true.\n",
      "3d • 3 days ago\n",
      "Follow\n",
      "\n",
      "No alternative text description for this imageActivate to view larger image\n",
      "likelovecelebrate\n",
      "68,665\n",
      "Khem Raj Pokhrel and 68,664 others\n",
      "1,154 comments\n",
      "\n",
      "Like\n",
      "\n",
      "Comment\n",
      "\n",
      "Share\n",
      "\n",
      "Send\n",
      "\n",
      "Show more results\n",
      "Add to your feed\n",
      "\n",
      "National Association of REALTORS®;realtors@bbn.com \n",
      "National Association of REALTORS®\n",
      "Company • Real Estate\n",
      "\n",
      "Follow\n",
      "Suze Orman\n",
      "Suze Orman\n",
      "Bestselling Author | Host of the Women & Money Podcast | Co-Founder of SecureSave\n",
      "\n",
      "Follow\n",
      "National Association of Home Builders\n",
      "National Association of Home Builders\n",
      "Company • Construction\n",
      "\n",
      "Follow\n",
      "View all recommendations \n",
      "\n",
      "About\n",
      "Accessibility\n",
      "Help Center\n",
      "\n",
      "Privacy & Terms \n",
      "Ad Choices\n",
      "Advertising\n",
      "\n",
      "Business Services \n",
      "Get the LinkedIn app\n",
      "More\n",
      " LinkedIn Corporation © 2022 info@content.linkedin.com \n",
      "Rabindra KharelStatus is online\n",
      "MessagingYou are on the messaging overlay. Press enter to open the list of conversations.\n",
      "\n",
      "\n",
      "Compose message\n",
      "\n",
      "You are on the messaging overlay. Press enter to open the list of conversations.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "\n",
    "f = open(\"C:\\\\Users\\\\super\\Downloads\\\\Week 1 Test\\\\websiteData.txt\", \"r\", encoding=\"utf8\")\n",
    "print(f.read())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['Jobs@linkedin.com']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['gregor@mxanalytics.com']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['susan.daniels@moo.com']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['aayush@deepminds.xyz']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['hr@vancuemonics.com']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['syneca.gregory@gmail.com']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['realtors@bbn.com']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "['info@content.linkedin.com']\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n",
      "[]\n"
     ]
    }
   ],
   "source": [
    "f = open(\"C:\\\\Users\\\\super\\Downloads\\\\Week 1 Test\\\\websiteData.txt\", \"r\", encoding=\"utf8\")\n",
    "\n",
    "for line in f:\n",
    "   \n",
    "    s = line.strip()\n",
    "  \n",
    "    \n",
    "    reg = re.findall(r\"[A-Za-z0-9._%+-]+\"\n",
    "                     r\"@[A-Za-z0-9.-]+\"\n",
    "                     r\"\\.[A-Za-z]{2,4}\", s)\n",
    "  \n",
    "   \n",
    "    print(reg)\n",
    "    \n",
    "  \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
